In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [42]:
#to view entire data
for chunk in pd.read_csv('goal15.forest_shares.csv', chunksize=10):
    print(chunk)

  iso3c  forests_2000  forests_2020  trend
0   AFG           1.9           1.9    0.0
1   ALB          28.1          28.8    2.5
2   DZA           0.7           0.8   14.3
3   ASM          88.7          85.7   -3.4
4   AND          34.0          34.0    0.0
5   AGO          62.3          53.4  -14.3
6   AIA          61.1          61.1    0.0
7   ATG          21.5          18.5  -14.0
8   ARG          12.2          10.4  -14.8
9   ARM          11.7          11.5   -1.7
   iso3c  forests_2000  forests_2020  trend
10   ABW           2.3           2.3    0.0
11   AUS          17.2          17.4    1.2
12   AUT          46.5          47.3    1.7
13   AZE          12.0          13.7   14.2
14   BHS          50.9          50.9    0.0
15   BHR           0.5           0.9   80.0
16   BGD          14.8          14.5   -2.0
17   BRB          14.7          14.7    0.0
18   BLR          40.8          43.2    5.9
19   BEL          22.0          22.8    3.6
   iso3c  forests_2000  forests_2020  trend
20   BLZ          64.0          56.0  -12.5
21   BEN          36.7          27.8  -24.3
22   BMU          18.5          18.5    0.0
23   BTN          65.5          71.4    9.0
24   BOL          50.9          46.9   -7.9
25   BES           5.9           5.9    0.0
26   BIH          41.2          42.7    3.6
27   BWA          31.1          26.9  -13.5
28   BRA          65.9          59.4   -9.9
29   VGB          24.5          24.1   -1.6
   iso3c  forests_2000  forests_2020  trend
30   BRN          75.3          72.1   -4.2
31   BGR          30.5          35.9   17.7
32   BFA          26.4          22.7  -14.0
33   BDI           7.6          10.9   43.4
34   CPV           9.9          11.3   14.1
35   KHM          61.1          45.7  -25.2
36   CMR          45.7          43.0   -5.9
37   CAN          38.8          38.7   -0.3
38   CYM          53.9          53.0   -1.7
39   CAF          36.8          35.8   -2.7
   iso3c  forests_2000  forests_2020  trend
40   TCD           5.0           3.4  -32.0
41   CHL          21.3          24.5   15.0
42   CHN          18.8          23.3   23.9
43   COL          56.5          53.3   -5.7
44   COM          22.4          17.7  -21.0
45   COG          65.0          64.3   -1.1
46   COK          64.9          65.0    0.2
47   CRI          56.0          59.4    6.1
48   CIV          16.0           8.9  -44.4
49   HRV          33.7          34.6    2.7
   iso3c  forests_2000  forests_2020  trend
50   CUB          22.7          31.2   37.4
51   CUW           0.2           0.2    0.0
52   CYP          18.6          18.7    0.5
53   CZE          34.1          34.7    1.8
54   PRK          53.6          50.1   -6.5
55   COD          63.5          55.6  -12.4
56   DNK          14.3          15.7    9.8
57   DJI           0.2           0.3   50.0
58   DMA          63.8          63.8    0.0
59   DOM          40.8          44.4    8.8
   iso3c  forests_2000  forests_2020  trend
60   ECU          55.3          50.3   -9.0
61   EGY           0.1           0.0 -100.0
62   SLV          32.5          28.2  -13.2
63   GNQ          93.2          87.3   -6.3
64   ERI           9.2           8.7   -5.4
65   EST          52.8          56.1    6.3
66   SWZ          27.5          28.9    5.1
67   ETH          16.4          15.1   -7.9
68   FLK           0.0           0.0    NaN
69   FRO           0.1           0.1    0.0
   iso3c  forests_2000  forests_2020  trend
70   FJI          55.1          62.4   13.2
71   FIN          73.7          73.7    0.0
72   FRA          27.9          31.5   12.9
73   GUF          97.7          96.6   -1.1
74   PYF          42.8          43.1    0.7
75   GAB          92.0          91.3   -0.8
76   GMB          35.3          24.0  -32.0
77   GEO          39.7          40.6    2.3
78   DEU          32.5          32.7    0.6
79   GHA          38.9          35.1   -9.8
   iso3c  forests_2000  forests_2020  trend
80   GIB           0.0           0.0    NaN
81   GRC          27.9          30.3    8.6
82   GRL           0.0           0.0    NaN
83   GRD          52.1          52.1    0.0
84   GLP          42.8          44.4    3.7
85   GUM          44.4          51.9   16.9
86   GTM          39.3          32.9  -16.3
87   GGY           2.9           5.4   86.2
88   GIN          28.2          25.2  -10.6
89   GNB          76.4          70.4   -7.9
   iso3c  forests_2000  forests_2020  trend
90   GUY          94.3          93.6   -0.7
91   HTI          13.8          12.6   -8.7
92   VAT           0.0           0.0    NaN
93   HND          60.6          56.8   -6.3
94   HUN          21.4          22.5    5.1
95   ISL           0.3           0.5   66.7
96   IND          22.7          24.3    7.0
97   IDN          53.9          49.1   -8.9
98   IRN           5.7           6.6   15.8
99   IRQ           1.9           1.9    0.0
    iso3c  forests_2000  forests_2020  trend
100   IRL           9.2          11.4   23.9
101   IMN           6.1           6.1    0.0
102   ISR           7.1           6.5   -8.5
103   ITA          28.3          32.3   14.1
104   JAM          48.1          55.1   14.6
105   JPN          68.2          68.4    0.3
106   JEY           5.0           5.0    0.0
107   JOR           1.1           1.1    0.0
108   KAZ           1.2           1.3    8.3
109   KEN           7.0           6.3  -10.0
    iso3c  forests_2000  forests_2020  trend
110   KIR           1.5           1.5    0.0
111   KWT           0.3           0.4   33.3
112   KGZ           6.2           6.9   11.3
113   LAO          75.5          71.9   -4.8
114   LVA          52.1          54.8    5.2
115   LBN          13.5          14.0    3.7
116   LSO           1.1           1.1    0.0
117   LBR          85.4          79.1   -7.4
118   LBY           0.1           0.1    0.0
119   LIE          41.9          41.9    0.0
    iso3c  forests_2000  forests_2020  trend
120   LTU          32.2          35.1    9.0
121   LUX          33.7          34.5    2.4
122   MDG          22.4          21.4   -4.5
123   MWI          32.7          23.8  -27.2
124   MYS          59.9          58.2   -2.8
125   MDV           2.7           2.7    0.0
126   MLI          10.9          10.9    0.0
127   MLT           1.1           1.4   27.3
128   MHL          52.2          52.2    0.0
129   MTQ          46.0          49.3    7.2
    iso3c  forests_2000  forests_2020  trend
130   MRT           0.4           0.3  -25.0
131   MUS          20.7          19.1   -7.7
132   MYT          41.9          37.1  -11.5
133   MEX          35.2          33.8   -4.0
134   FSM          91.2          92.0    0.9
135   MCO           0.0           0.0    NaN
136   MNG           9.2           9.1   -1.1
137   MNE          46.5          61.5   32.3
138   MSR          25.0          25.0    0.0
139   MAR          12.3          12.9    4.9
    iso3c  forests_2000  forests_2020  trend
140   MOZ          52.4          46.7  -10.9
141   MMR          53.4          43.7  -18.2
142   NAM           9.8           8.1  -17.3
143   NRU           0.0           0.0    NaN
144   NPL          41.7          41.6   -0.2
145   NLD          10.6          11.0    3.8
146   NCL          45.8          45.8    0.0
147   NZL          37.4          37.6    0.5
148   NIC          44.9          28.3  -37.0
149   NER           1.0           0.9  -10.0
    iso3c  forests_2000  forests_2020  trend
150   NGA          27.3          23.7  -13.2
151   NIU          72.4          72.6    0.3
152   NFK          12.2          12.2    0.0
153   MKD          37.7          39.7    5.3
154   MNP          69.5          53.0  -23.7
155   NOR          39.8          40.1    0.8
156   OMN           0.0           0.0    NaN
157   PAK           5.9           4.8  -18.6
158   PLW          86.0          90.0    4.7
159   PAN          59.8          56.8   -5.0
    iso3c  forests_2000  forests_2020  trend
160   PNG          80.1          79.2   -1.1
161   PRY          57.9          40.5  -30.1
162   PER          58.8          56.5   -3.9
163   PHL          24.5          24.1   -1.6
164   PCN          74.5          74.5    0.0
165   POL          29.6          31.0    4.7
166   PRT          35.9          36.2    0.8
167   PRI          48.4          56.0   15.7
168   QAT           0.0           0.0    NaN
169   KOR          67.1          64.4   -4.0
    iso3c  forests_2000  forests_2020  trend
170   MDA          10.5          11.8   12.4
171   REU          36.4          39.2    7.7
172   ROU          27.7          30.1    8.7
173   RUS          49.4          49.8    0.8
174   RWA          11.6          11.2   -3.4
175   BLM           8.5           8.5    0.0
176   SHN           5.1           5.1    0.0
177   KNA          42.3          42.3    0.0
178   LCA          34.4          34.0   -1.2
179   MAF          24.8          24.8    0.0
    iso3c  forests_2000  forests_2020  trend
180   SPM           7.3           5.3  -27.4
181   VCT          73.2          73.2    0.0
182   WSM          60.5          57.1   -5.6
183   SMR          16.7          16.7    0.0
184   STP          60.8          54.1  -11.0
185   SAU           0.5           0.5    0.0
186   SEN          46.0          41.9   -8.9
187   SRB          28.1          31.1   10.7
188   SYC          73.3          73.3    0.0
189   SLE          40.6          35.1  -13.5
    iso3c  forests_2000  forests_2020  trend
190   SGP          25.4          21.7  -14.6
191   SXM          10.9          10.9    0.0
192   SVK          39.5          40.1    1.5
193   SVN          61.2          61.5    0.5
194   SLB          90.7          90.1   -0.7
195   SOM          12.0           9.5  -20.8
196   ZAF          14.7          14.1   -4.1
197   SSD          11.3          11.3    0.0
198   ESP          34.3          37.2    8.5
199   LKA          34.5          34.2   -0.9
    iso3c  forests_2000  forests_2020  trend
200   PSE           1.5           1.7   13.3
201   SDN          11.8           9.9  -16.1
202   SUR          98.3          97.4   -0.9
203   SJM           0.0           0.0    NaN
204   SWE          69.1          68.7   -0.6
205   CHE          30.3          32.1    5.9
206   SYR           2.4           2.8   16.7
207   TJK           2.9           3.1    6.9
208   THA          37.2          38.9    4.6
209   TLS          63.8          61.9   -3.0
    iso3c  forests_2000  forests_2020  trend
210   TGO          23.3          22.2   -4.7
211   TKL           0.0           0.0    NaN
212   TON          12.4          12.4    0.0
213   TTO          46.1          44.5   -3.5
214   TUN           4.3           4.5    4.7
215   TUR          26.2          28.9   10.3
216   TKM           8.8           8.8    0.0
217   TCA          11.1          11.1    0.0
218   TUV          33.3          33.3    0.0
219   UGA          15.8          11.7  -25.9
    iso3c  forests_2000  forests_2020  trend
220   UKR          16.4          16.7    1.8
221   ARE           4.4           4.5    2.3
222   GBR          12.2          13.2    8.2
223   TZA          60.6          51.6  -14.9
224   USA          33.1          33.9    2.4
225   VIR          58.5          56.9   -2.7
226   URY           7.8          11.6   48.7
227   UZB           6.8           8.4   23.5
228   VUT          36.3          36.3    0.0
229   VEN          55.7          52.4   -5.9
    iso3c  forests_2000  forests_2020  trend
230   VNM          37.9          46.7   23.2
231   WLF          41.5          41.6    0.2
232   ESH           2.5           2.5    0.0
233   WLD          31.9          31.2   -2.2
234   YEM           1.0           1.0    0.0
235   ZMB          63.3          60.3   -4.7
236   ZWE          47.5          45.1   -5.1

In [46]:
#resetting the df for future use
df=pd.read_csv('goal15.forest_Shares.csv')
df

    iso3c  forests_2000  forests_2020  trend
0     AFG           1.9           1.9    0.0
1     ALB          28.1          28.8    2.5
2     DZA           0.7           0.8   14.3
3     ASM          88.7          85.7   -3.4
4     AND          34.0          34.0    0.0
..    ...           ...           ...    ...
232   ESH           2.5           2.5    0.0
233   WLD          31.9          31.2   -2.2
234   YEM           1.0           1.0    0.0
235   ZMB          63.3          60.3   -4.7
236   ZWE          47.5          45.1   -5.1

[237 rows x 4 columns]

In [57]:
#rough idea about the dataset . would focus on trend now
df.describe()

       forests_2000  forests_2020       trend
count    237.000000    237.000000  227.000000
mean      32.255274     31.585654    0.104846
std       25.366225     24.744673   16.863427
min        0.000000      0.000000 -100.000000
25%        9.900000     10.400000   -5.500000
50%       30.300000     30.300000    0.000000
75%       50.900000     49.800000    4.650000
max       98.300000     97.400000   86.200000

In [59]:
#sort by trend starting from lowest to see which country lost the most amount of forests/trees
df.sort_values('trend')

    iso3c  forests_2000  forests_2020  trend
61    EGY           0.1           0.0 -100.0
48    CIV          16.0           8.9  -44.4
148   NIC          44.9          28.3  -37.0
40    TCD           5.0           3.4  -32.0
76    GMB          35.3          24.0  -32.0
..    ...           ...           ...    ...
143   NRU           0.0           0.0    NaN
156   OMN           0.0           0.0    NaN
168   QAT           0.0           0.0    NaN
203   SJM           0.0           0.0    NaN
211   TKL           0.0           0.0    NaN

[237 rows x 4 columns]

In [158]:
#removing all trends = 0 , which means no change has taken place thus useless
df = df[df["trend"] !=0.0]
df

    iso3c  forests_2000  forests_2020  trend
1     ALB          28.1          28.8    2.5
2     DZA           0.7           0.8   14.3
3     ASM          88.7          85.7   -3.4
5     AGO          62.3          53.4  -14.3
7     ATG          21.5          18.5  -14.0
..    ...           ...           ...    ...
230   VNM          37.9          46.7   23.2
231   WLF          41.5          41.6    0.2
233   WLD          31.9          31.2   -2.2
235   ZMB          63.3          60.3   -4.7
236   ZWE          47.5          45.1   -5.1

[181 rows x 4 columns]

In [160]:
#reseting index to move forward
df.reset_index()
df.to_csv('removedtrends.csv',index=True)

In [164]:
#making checkipoint 1
df=pd.read_csv('removedtrends.csv')
df

     Unnamed: 0 iso3c  forests_2000  forests_2020  trend
0             1   ALB          28.1          28.8    2.5
1             2   DZA           0.7           0.8   14.3
2             3   ASM          88.7          85.7   -3.4
3             5   AGO          62.3          53.4  -14.3
4             7   ATG          21.5          18.5  -14.0
..          ...   ...           ...           ...    ...
176         230   VNM          37.9          46.7   23.2
177         231   WLF          41.5          41.6    0.2
178         233   WLD          31.9          31.2   -2.2
179         235   ZMB          63.3          60.3   -4.7
180         236   ZWE          47.5          45.1   -5.1

[181 rows x 5 columns]

In [285]:
#remnamed the column 
df=pd.read_csv('removedtrends.csv')
df.rename(columns={"Unnamed: 0":"Index"},inplace=True)
df

     Index iso3c  forests_2000  forests_2020  trend
0        1   ALB          28.1          28.8    2.5
1        2   DZA           0.7           0.8   14.3
2        3   ASM          88.7          85.7   -3.4
3        5   AGO          62.3          53.4  -14.3
4        7   ATG          21.5          18.5  -14.0
..     ...   ...           ...           ...    ...
176    230   VNM          37.9          46.7   23.2
177    231   WLF          41.5          41.6    0.2
178    233   WLD          31.9          31.2   -2.2
179    235   ZMB          63.3          60.3   -4.7
180    236   ZWE          47.5          45.1   -5.1

[181 rows x 5 columns]

In [287]:
#removing the data with no forests to start and to end with (redundant)
df = df[~((df["forests_2000"] == 0.0) & (~(df["forests_2020"] == 0.0)))]
df
df.sort_values('trend',ascending=False)

     Index iso3c  forests_2000  forests_2020  trend
70      87   GGY           2.9           5.4   86.2
10      15   BHR           0.5           0.9   80.0
77      95   ISL           0.3           0.5   66.7
48      57   DJI           0.2           0.3   50.0
173    226   URY           7.8          11.6   48.7
..     ...   ...           ...           ...    ...
126    161   PRY          57.9          40.5  -30.1
62      76   GMB          35.3          24.0  -32.0
32      40   TCD           5.0           3.4  -32.0
115    148   NIC          44.9          28.3  -37.0
40      48   CIV          16.0           8.9  -44.4

[181 rows x 5 columns]

In [289]:
#!pip install country_converter
import country_converter as coco
df["Country_Name"]=coco.convert(names=df["iso3c"],to="name")
df
#Getting an error that code WLD not found in ISO3

WLD not found in ISO3

     Index iso3c  forests_2000  forests_2020  trend               Country_Name
0        1   ALB          28.1          28.8    2.5                    Albania
1        2   DZA           0.7           0.8   14.3                    Algeria
2        3   ASM          88.7          85.7   -3.4             American Samoa
3        5   AGO          62.3          53.4  -14.3                     Angola
4        7   ATG          21.5          18.5  -14.0        Antigua and Barbuda
..     ...   ...           ...           ...    ...                        ...
176    230   VNM          37.9          46.7   23.2                    Vietnam
177    231   WLF          41.5          41.6    0.2  Wallis and Futuna Islands
178    233   WLD          31.9          31.2   -2.2                  not found
179    235   ZMB          63.3          60.3   -4.7                     Zambia
180    236   ZWE          47.5          45.1   -5.1                   Zimbabwe

[181 rows x 6 columns]

In [365]:
#using filter i find that row and remove it
df.loc[df['iso3c']=='WLD']
#df=df.drop(178)
df=df.to_csv('added_country.csv')

In [251]:
df

     Index iso3c  forests_2000  forests_2020  trend               Country_Name
0        1   ALB          28.1          28.8    2.5                    Albania
1        2   DZA           0.7           0.8   14.3                    Algeria
2        3   ASM          88.7          85.7   -3.4             American Samoa
3        5   AGO          62.3          53.4  -14.3                     Angola
4        7   ATG          21.5          18.5  -14.0        Antigua and Barbuda
..     ...   ...           ...           ...    ...                        ...
175    229   VEN          55.7          52.4   -5.9                  Venezuela
176    230   VNM          37.9          46.7   23.2                    Vietnam
177    231   WLF          41.5          41.6    0.2  Wallis and Futuna Islands
179    235   ZMB          63.3          60.3   -4.7                     Zambia
180    236   ZWE          47.5          45.1   -5.1                   Zimbabwe

[180 rows x 6 columns]

In [369]:
#checkpoint 2
df=pd.read_csv('added_country.csv')
#deleted the redundant index
#del df["Index"]
#del df["Unnamed: 0"]
df=df.to_csv('removed_index.csv')

In [405]:
#shifting country name column to the front 
df=pd.read_csv('removed_index.csv')
df = df[[df.columns[-1]] + list(df.columns[:-1])]
df=df.sort_values('trend',ascending=False)
#del df["Unnamed: 0.1"]
#del df["Unnamed: 0"]
df=df.to_csv('sorted_by_trend.csv',index=False)

In [411]:
df=pd.read_csv("sorted_by_trend.csv")
#del df["Unnamed: 0.1"]
#del df["Unnamed: 0"]
df

     trend   Country_Name iso3c  forests_2000  forests_2020
0     86.2       Guernsey   GGY           2.9           5.4
1     80.0        Bahrain   BHR           0.5           0.9
2     66.7        Iceland   ISL           0.3           0.5
3     50.0       Djibouti   DJI           0.2           0.3
4     48.7        Uruguay   URY           7.8          11.6
..     ...            ...   ...           ...           ...
175  -30.1       Paraguay   PRY          57.9          40.5
176  -32.0         Gambia   GMB          35.3          24.0
177  -32.0           Chad   TCD           5.0           3.4
178  -37.0      Nicaragua   NIC          44.9          28.3
179  -44.4  Cote d'Ivoire   CIV          16.0           8.9

[180 rows x 5 columns]

In [417]:
# Reorder the columns
df = df[['iso3c', 'Country_Name', 'trend', 'forests_2000', 'forests_2020']]
df
df=df.to_csv("cleaneddeforestation.csv",index=False)

In [427]:
#make everything easier to read by removing decimels
df=pd.read_csv('cleaneddeforestation.csv')
df['trend'] = df['trend'].round(0)
df['forests_2000'] = df['forests_2000'].round(0)
df['forests_2020'] = df['forests_2020'].round(0)
df
df['trend'] = df['trend'].astype(int)
df['forests_2000'] = df['forests_2000'].astype(int)
df['forests_2020'] = df['forests_2020'].astype(int)

df

    iso3c   Country_Name  trend  forests_2000  forests_2020
0     GGY       Guernsey     86             3             5
1     BHR        Bahrain     80             0             1
2     ISL        Iceland     67             0             0
3     DJI       Djibouti     50             0             0
4     URY        Uruguay     49             8            12
..    ...            ...    ...           ...           ...
175   PRY       Paraguay    -30            58            40
176   GMB         Gambia    -32            35            24
177   TCD           Chad    -32             5             3
178   NIC      Nicaragua    -37            45            28
179   CIV  Cote d'Ivoire    -44            16             9

[180 rows x 5 columns]

In [433]:
#make index start from 1
df.reset_index(drop=True, inplace=True)  # Reset index, dropping the old one
df.index = df.index + 1  # Shift index to start from 1
df

    iso3c   Country_Name  trend  forests_2000  forests_2020
1     GGY       Guernsey     86             3             5
2     BHR        Bahrain     80             0             1
3     ISL        Iceland     67             0             0
4     DJI       Djibouti     50             0             0
5     URY        Uruguay     49             8            12
..    ...            ...    ...           ...           ...
176   PRY       Paraguay    -30            58            40
177   GMB         Gambia    -32            35            24
178   TCD           Chad    -32             5             3
179   NIC      Nicaragua    -37            45            28
180   CIV  Cote d'Ivoire    -44            16             9

[180 rows x 5 columns]

In [441]:
#remove all the new forests_2000 and forests_2020 = 0
df = df[~((df["forests_2000"] == 0.0) & (~(df["forests_2020"] == 0.0)))]
df
df=df.to_csv('cleaned_deforestation.csv')